const {
  productsTable,
  loansTable,
  faqsTable,
  contactBranchesTable,
  aboutUsTable,
  servicesTable,
  messagesTable,
  statsTable,
  whatWeDoTable,
  socialsTable,
  testimoniesTable,
  partnersTable,
  adminEmail,
  adminUsername,
  adminPassword,
  adminPin,
} = require("../models/schema");

const db = require("../db/db");

module.exports = {
  adminEmail,
  adminUsername,
  adminPassword,
  adminPin,
  productsTable,
  contactBranchesTable,
  whatWeDoTable,
  statsTable,
  aboutUsTable,
  loansTable,
  socialsTable,
  messagesTable,
  partnersTable,
  servicesTable,
  testimoniesTable,
  faqsTable,
  db,
};
